### ISSUE TITLE
Overlaps with xSQLServer

### ISSUE THREAD

**Issue by rhencke** [PowerShell/xSqlPs#3] opened 2015-05-22 17:34 UTC
There is overlap between this module and https://github.com/PowerShell/xSQLServer/.

For example, MSFT_xSqlServerInstall from this module fulfills the same role as MSFT_xSqlServerSetup from xSQLServer.

Perhaps these two modules could be combined into one?

**Comment by vors** [comment] 2015-05-22 17:34
:+1:

**Comment by Matticusau** [comment] 2015-06-05 13:14
I agree, if you read the original DSC Resource Kit notes for xSQLServer it was designed to support System Center installations. I have been working on enhancing this xSqlPs to even more greatly support our best practices for SQL installs, just trying to get it to a point that the team will accept it into the release

**Comment by rhencke** [comment] 2015-06-05 14:09
@Matticusau I like your dogs! :)

That's awesome.  I have done the same, but unfortunately I'm still working with my employer on getting clearance to submit it back.  But, I'd be very very interested in what you are working on there.  If you need anyone to hammer on it and try it out let me know!

**Comment by DdenBraver** [comment] 2015-11-17 11:11
Just reading past this "issue".
Some time ago I was running into the same issue, and merged the modules xSQLServer and xSQLPs  into a custom resource. 

@Matticusau as I understand that xSQLServer was created to support System Center installations, it   currently still supports much more parameters for the installation, making it easyer to finetune the installations.

I will upload my custom resource as an example if my customer allows me to share the code.

**Comment by kilasuit** [comment] 2016-03-13 12:25
@KarolKaczmarek  - This should be merged together with xSQLServer Resource for a few reasons
- Simpler Adoption & removes the existing overlap between the two modules.
- Simpler Management & Development to be able to build a single fully featured resource (Ideal end goal)

I'm dedicating some time to work to doing this where I can but this is something that in my opinion we need to start down that path as soon as we can

**Comment by Matticusau** [comment] 2016-03-16 01:05
This is a great discussion. I have actually had some discussions around this internally and am continuing those discussions because internally we feel the two should be merged and the view from the community definitely supports that approach too which is helping to drive the discussions. It will need to be a community approach (IMO) and when I have some clarity around how that looks I will provide further guidance.
Matt

**Comment by DdenBraver** [comment] 2016-03-16 08:40
@Matticusau If there is any way I could help with this, please let me know.
I have no problem "merging" the 2 resources together, and remove any duplicates if this might help.
Personally I feel that we should continue on the name xSQLServer, as not everything has to be SQLPs based.

**Comment by KarolKaczmarek** [comment] 2016-04-27 23:27
Agreed, we should merge xSqlPs into xSQLServer and retire this repo.
I saw @DdenBraver already started working on this with https://github.com/Solvinity/cSQLServer .
Would you or anyone else be willing to drive this and submit PR into xSQLServer?

**Comment by Matticusau** [comment] 2016-11-16 07:57
The work to merge into xSqlServer has already been completed for some time (sorry forgot to update this). I will chase up about retiring the repo

**Comment by kwirkykat** [comment] 2017-01-26 22:30
@johlju Looks like this module is a duplicate of xSqlServer? Any reason I shouldn't remove/deprecate this module?

**Comment by johlju** [comment] 2017-01-27 16:09
@kwirkykat I think we should deprecate this module. There are equivalent resources, and soon to be better resources (IMHO). Might be a good thing to deprecate it for a couple of months and then remove it. So people have a chance to move to the new module.

| Resource in xSqlPs | equivalent in xSQLServer |
| --- | --- |
| MSFT_xSqlHAEndPoint | MSFT_xSQLServerEndpoint |
| MSFT_xSqlAlias | MSFT_xSQLServerAlias |
| MSFT_xSqlHAGroup | MSFT_xSQLServerAlwaysOnAvailabilityGroup + MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica |
| MSFT_xSqlHAService | MSFT_xSQLServerAlwaysOnService |
| MSFT_xSqlServerInstall | MSFT_xSQLServerSetup |
| MSFT_xWaitForSqlHAGroup | MSFT_xWaitForAvailabilityGroup (and might be replaced by MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica) |

UPDATE 2017-07-12: Updated table and removed deprecated resource no longer in xSQLServer.

**Comment by johlju** [comment] 2017-04-18 20:12
@kwirkykat You may remove this module at anytime. This module is obsolete now!

**Comment by andikrueger** [comment] 2017-04-20 12:58
Today I came across the "modified Version" of this module in this azure [quickstart template](https://github.com/Azure/azure-quickstart-templates/blob/master/sharepoint-server-farm-ha/dscv2/ConfigureAlwaysOnSqlServer.ps1.zip) named xSql.
The modified version contains "MicrosoftAzure_xSqlLogin" wich allows the configuration of SQL logins on instance level. This function seems to be missing in xSqlPs and xSqlServer. 

@kwirkykat and @johlju: Are there any plans to integrate these modifications in any of the existing or newer xSql modules?

**Comment by johlju** [comment] 2017-04-20 15:59
@andikrueger There is xSQLServerLogin resource in the module xSQLServer that can create logins. If you are missing any functionality in that resource, please submit an issue in https://github.com/PowerShell/xSQLServer and we can discuss it there. 😄

**Comment by johlju** [comment] 2017-04-20 16:08
@andikrueger That seems to be a subset of resource from different modules compiled for a specific scenario (use case). Deployed to https://azure.microsoft.com/en-us/resources/templates/ by different users. So for them to be added to DSC Resource Kit the authors/owners need to send them in as PR's (Pull Requests).

**Comment by kwirkykat** [comment] 2017-07-11 23:35
This module has been deprecated. Leaving this as the only open issue for now.

**Comment by johlju** [comment] 2018-05-03 12:55
Closing this as per previous comment. Please reopen or comment if this was closed in error.

**Closed as completed by johlju** 2018-05-03 12:55 UTC
